#!/usr/bin/env bash


java_path=$(ls /usr/lib/jvm |grep java)
exec /usr/lib/jvm/$java_path/jre/bin/java -cp /var/lang/lib/python3.8/site-packages/pyspark/conf/:/var/lang/lib/python3.8/site-packages/pyspark/jars/* -Xmx1g "$@"

